name: Network Test

on:
  workflow_dispatch:

jobs:
  test-network:
    runs-on: ubuntu-latest
    steps:
    - name: Test FTP port connectivity
      run: |
        # Test if FTP port is open
        timeout 10s nc -z -v -w 5 50.30.32.124 21 && echo "FTP port 21 is open" || echo "FTP port 21 is closed"
        
        # Test if we can establish basic connection
        timeout 10s bash -c 'echo "QUIT" | nc 50.30.32.124 21' || echo "Cannot connect to FTP"
