name: FTP Test
on: 
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test-ftp:
    runs-on: ubuntu-latest
    steps:
    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y ftp

    - name: Test FTP connection
      run: |
        # Create FTP commands file
        cat > ftp_commands.txt << 'EOF'
        user deploynew@okanologistics.com Deployer@123!
        pwd
        ls
        quit
        EOF
        
        # Run FTP with timeout
        timeout 30s ftp -n -v 50.30.32.124 < ftp_commands.txt || echo "FTP test completed"
