- name: 📂 Deploy to FTP
  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: 50.30.32.124
    username: ${{ secrets.FTP_USER }}
    password: ${{ secrets.FTP_PASS }}
    protocol: ftps
    local-dir: ./   # your build folder
    server-dir: /public_html
