name: FTP Deploy

on:
  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install ftp
      run: sudo apt-get update && sudo apt-get install -y ftp

    - name: Test FTP with built-in timeout
      run: |
        # Create FTP command script
        cat > ftp_commands.txt << EOF
        user deploynew@okanologistics.com Deployer@123!
        pwd
        ls
        quit
        EOF
        
        # Run with built-in timeout
        timeout 30s ftp -n -v 50.30.32.124 < ftp_commands.txt || echo "FTP timed out"
