name: Deploy via FTP

on:
  push:
    branches: [ main ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Discover and create directory structure
        run: |
          lftp -e "
            set ftp:passive-mode off;
            set ftp:ssl-allow no;
            open -u 'deploynew@okanologistics.com','Deployer@123!' ftp://50.30.32.124;
            echo 'Current directory:';
            pwd;
            echo 'Listing contents:';
            ls -la;
            echo 'Creating public_html directory...';
            mkdir -p public_html;
            echo 'Changing to public_html...';
            cd public_html;
            echo 'Now in:';
            pwd;
            bye
          "
