name: Debug FTP Structure

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug FTP connection
        run: |
          lftp -e "
            set ftp:passive-mode off;
            open -u 'deploynew@okanologistics.com','Deployer@123!' ftp://50.30.32.124;
            echo '=== CURRENT DIRECTORY ===';
            pwd;
            echo '=== DIRECTORY CONTENTS ===';
            ls -la;
            echo '=== ATTEMPTING TO CREATE public_html ===';
            mkdir public_html;
            echo '=== CHECKING IF public_html EXISTS NOW ===';
            ls -la;
            echo '=== ATTEMPTING TO CHANGE TO public_html ===';
            cd public_html;
            echo '=== SUCCESS! IN public_html DIRECTORY ===';
            pwd;
            bye
          "
