name: FTP Deploy

on:
  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Debug FTP connection with timeout
      run: |
        timeout 30s bash -c "
          lftp -e \"
            set ftp:passive-mode off
            set ftp:ssl-allow no
            set net:timeout 5
            set net:max-retries 2
            open -u 'deploynew@okanologistics.com','Deployer@123!' ftp://50.30.32.124
            echo '=== CURRENT DIRECTORY ==='
            pwd
            echo '=== DIRECTORY CONTENTS ==='
            ls -la
            bye
          \"
        " || echo "FTP command completed or timed out"
