name: FTP Deploy (Blind Upload)

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Blind Upload with lftp
        run: |
          lftp -c "
            set ssl:verify-certificate no;
            set ftp:list-options -a;
            open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ftps://50.30.32.124;
            cd /public_html;
            glob -a put -O . $(find . -type f);
            bye
          "
