name: Deploy via FTP

on:
  push:
    branches: [ main ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy files via FTP
        run: |
          lftp -e "
            set ftp:passive-mode off;
            set ftp:ssl-allow no;
            set net:timeout 30;
            set net:max-retries 3;
            open -u 'deploynew@okanologistics.com','Deployer@123!' ftp://50.30.32.124;
            cd public_html;
            mirror -R -v -x '.git/' -x '.github/' . .;
            bye
          "
