name: Deploy via FTP

on:
  push:
    branches: [ main ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload via FTP (Active Mode)
        run: |
          lftp -e "
            set ftp:passive-mode off;
            set ftp:ssl-allow no;
            open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ftp://50.30.32.124;
            cd public_html;
            mirror -R -v . .;
            bye
          "
